export const pattern5 = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVBBBVVBBVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVVVVVVBBX",
    "XBXVXVXBXVXVXVX",
    "XVVVVVVBVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XVVVVVBVVVVVVBX",
    "XVXVXVXVXBXVXVX",
    "XVVVVVVBBVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVBBVVVVVX",
    "XBXBXVXVXVXVXVX",
    "XVVVVVVVVBVVVVX",
    "XXXXXXXXXXXXXXX"
];

export const pattern1 = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVVVVVVBBX",
    "XBXVXVXBXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVBVVVVVBX",
    "XVXVXVXVXBXVXVX",
    "XVVVVVVBBVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVBBVVVVVX",
    "XBXBXVXVXVXVXVX",
    "XVVVVVVVVBVVVVX",
    "XXXXXXXXXXXXXXX"
];
export const pattern2 = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVBBBVVBBVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVVVVVVBBX",
    "XBXVXVXBXVXVXVX",
    "XVVVVVVBVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XVVVVVBVVVVVVBX",
    "XVXVXVXVXBXVXVX",
    "XVVVVVVBBVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVBBVVVVVX",
    "XBXBXVXVXVXVXVX",
    "XVVVVVVVVBVVVVX",
    "XXXXXXXXXXXXXXX"
];

export const pattern3 = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVBBBVVBBVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVVVVVVBBX",
    "XBXVXVXBXVXVXVX",
    "XVVVVVVBVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVBVVVVVBX",
    "XVXVXVXVXBXVXVX",
    "XVVVVVVBBVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVBBVVVVVX",
    "XBXBXVXVXVXVXVX",
    "XVVVVVVVVBVVVVX",
    "XXXXXXXXXXXXXXX"
];

export const pattern4 = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVBBBVVBBVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVVVVVVBBX",
    "XBXVXVXBXVXVXVX",
    "XVVVVVVBVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XVVVVVBVVVVVVBX",
    "XVXVXVXVXBXVXVX",
    "XVVVVVVBBVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVBBVVVVVX",
    "XBXBXVXVXVXVXVX",
    "XVVVVVVVVBVVVVX",
    "XXXXXXXXXXXXXXX"
];

export const pattern = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVBBBVVBBVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVVVVVVBBX",
    "XBXVXVXBXVXVXVX",
    "XVVVVVBVVVVVVVX",
    "XVXVXVXBXVXVXVX",
    "XBVVVVVBVVVVVBX",
    "XVXVXVXVXBXVXVX",
    "XVVVVVVBBVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVBBVVVVVX",
    "XBXBXVXVXVXVXVX",
    "XVVVVVVVVBVVVVX",
    "XXXXXXXXXXXXXXX"
];
