export const pattern = [
    "XXXXXXXXXXXXXXX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XVXVXVXVXVXVXVX",
    "XVVVVVVVVVVVVVX",
    "XXXXXXXXXXXXXXX"
];
